### ISSUE TITLE
Examples directory missing?

### ISSUE THREAD

**Issue by xunker** [javanthropus/archive-zip#13]
The readme mentions "More examples can be found in the examples directory of the source distribution", but I don't see that directory in the repo. Am I looking in the wrong place?

**Comment by javanthropus** [comment]
My intention was to provide examples, but the synopsis and documentation seem to have been enough for all these years. You're actually the first to ask about this. I should probably update the document, or would you like to see some specific example?

**Comment by xunker** [comment]
Don't feel the need to go to the trouble of adding a bunch of examples just for me; I did get 90% of what I needed from the readme.

Specifically, I was looking for information on how to remove a file from a zip archive.  The readme mentions being able to do that, too, and the old rubyforge docs show a `#remove_entry` method but I don't see that in the newer code.

I can fake it using this code:

```ruby
Archive::Zip.open(zip_filename, :w) do |zip|
  zip.instance_eval { @entries.reject!{|m| m.zip_path == file_i_want_to_delete} }
end
```

But that's a really brittle solution that could break in later versions.

**Comment by javanthropus** [comment]
A better way is to think of the zip archive like any other file you wish to edit.  The process is to create a new file with the edited content and then delete the old file.

```ruby
Archive::Zip.open(src_filename, :r) do |src|
  Archive::Zip.open(dst_filename, :w) do |dst|
    src.each do |entry|
      dst << entry unless entry.zip_path == file_i_want_to_delete
    end
  end
end
File.unlink(src_filename)
File.rename(dst_filename, src_filename)
```
The efficiency of this solution isn't great though because each entry is extracted in memory and then archived again.  Making this operation efficient would require some hackery unfortunately, but at least this solution should work safely.

I haven't tried this code, but see if it works for you.

**Comment by xunker** [comment]
Thanks, I'll check that out. For the time being I'm doing the even less efficient thing: extract the whole archive to disk, remove the file and archiving it all up again. You can see the madness I have created [here](https://github.com/xunker/multi_zip/blob/master/lib/multi_zip/backend/archive_zip.rb).

This work is for [a gem I am working on](https://github.com/xunker/multi_zip) that provides a standard interface to whatever zip/unzipping gems are currently available on your system.
