### ISSUE TITLE
The Archive module name is a too common name

### ISSUE THREAD

**Issue by juhat** [javanthropus/archive-zip#20]
Hi,

I arrived to this project, because chromedriver-helper gem uses it. However I can not use any of the gems in the project because the Archive module name collides with a project name what I can not change.

Wouldn't it be a good idea to use a bit more specific module name in this gem?

**Comment by javanthropus** [comment]
That kind of change would be a massive compatibility break.  It would also require that the chromedriver-helper gem be updated to use the new name before you would even be able to benefit from the change.

Given that this is the first such request for this project after all these years of existence, there will need to be more evidence that the current name is indeed an issue for a wider array of consumers or potential consumers before this request is considered further.  What is the project that you cannot change, and why can't you change it?

**Comment by javanthropus** [comment]
Closing for lack of a response.
