### ISSUE TITLE
How do you create an archive with no parent directory?

### ISSUE THREAD

**Issue by jcavalieri** [javanthropus/archive-zip#24]
Hi @javanthropus ,

When I create an archive with the following ...

```
Dir.mktmpdir do |tmp_dir|
  # some work
  Archive::Zip.archive(zip_path, tmp_dir)
end
```

... it includes the folder name of the temp name, e.g. `d20210615-17-16oijt3/`

How would I create an archive with no top folder?

Thanks,
John

**Comment by javanthropus** [comment]
Hi @jcavalieri,

This is actually covered in the examples:
https://rdoc.info/gems/archive-zip#synopsis

The second example for creating an archive shows how to create one with the contents of a directory without including the directory itself.  In short, just append `/.` to a directory path, and only the content of the directory will be added.

**Comment by jcavalieri** [comment]
Thanks @javanthropus!
